default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: support_issue_tracking_development

test:
  <<: *default
  database: support_issue_tracking_test

#production:
#  <<: *default
#  database: support_issue_tracking_production
#  username: support_issue_tracking
#  password: <%= ENV['SUPPORT_ISSUE_TRACKING_DATABASE_PASSWORD'] %>
